# Generated by Django 4.1 on 2024-07-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0002_upload_drop_down'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
