# Generated by Django 4.1 on 2024-07-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_app', '0003_alter_upload_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='drop_down',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=1),
        ),
    ]
